### ISSUE TITLE
react-anything benefits

### ISSUE THREAD

**Issue by larrybotha** [evilfer/react-anything#1]
What are the benefits of using react-anything over react? Is it primarily reduced file-size, or does it contribute to Phaser dev?

EDIT: whoops - nevermind. I see on https://github.com/evilfer/react-phaser that you are providing an API :)

**Comment by evilfer** [comment]
Hi Larry,

The goal behind react-anything is to make it easier to build alternative native implementations of react. react-phaser is one example, in which 'native nodes' manipulate Phaser objects instead of DOM elements or mobile native views).

What it does:
- removes the default DOM manipulation implementation from React (which affects what happens during a transaction, and how native or empty nodes are treated).
- provides a render function that initializes the VDOM. 
- allows injecting a native implementation by defining a set of hooks. Specifically, a native implementation simply needs to implement:

``` javascript

{
    components: {
        mount: function (id, tag, props, parent) {},
        unmount: function (node) {},        
        update: function (node, nextProps, lastProps) {}
    },
    transaction: {
        initialize: function () {},
        close: function (node) {}
    }
}
```

**Comment by larrybotha** [comment]
awesome, thanks @evilfer
